apiVersion: batch/v1
kind: Job
metadata:
  name: ms-schema
spec:
  template:
    spec:
      containers:
        - name: ms-schema
          # release v1.6.0
          image: quay.io/ukhomeofficedigital/ms-schema:e4a8f7be112bcf5a4380b0cfe49f743fa1232b36
          command: ["npm",  "run", "db:{{ .SCHEMA_ACTION }}"]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: rranotprod
                  key: endpoint
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: rranotprod
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: rranotprod
                  key: password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: rranotprod
                  key: db_name
            - name: NODE_ENV
              value: production
      restartPolicy: Never
  backoffLimit: 0
